name: Release builder
run-name: Build ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  
permissions:
  contents: write

jobs:
  builder-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set environment
      run: |
          export zlibArchive='https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.xz'
          export caresArchive='https://github.com/c-ares/c-ares/releases/download/cares-1_19_0/c-ares-1.19.0.tar.gz'
          export wolfSSLArchive='https://github.com/wolfSSL/wolfssl/archive/refs/tags/v5.6.0-stable.tar.gz'
          export nghttp2Archive='https://github.com/nghttp2/nghttp2/releases/download/v1.52.0/nghttp2-1.52.0.tar.xz'
          export curlArchive='https://github.com/curl/curl/releases/download/curl-8_0_1/curl-8.0.1.tar.xz'
          export TOOLCHAIN=$(pwd)/x86_64-linux-musl-native
          export AR=$TOOLCHAIN/bin/x86_64-linux-musl-gcc-ar
          export AS=$TOOLCHAIN/bin/as
          export CC=$TOOLCHAIN/bin/x86_64-linux-musl-gcc
          export CXX=$TOOLCHAIN/bin/x86_64-linux-musl-g++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/x86_64-linux-musl-gcc-ranlib
          export STRIP=$TOOLCHAIN/bin/strip
    
    - name: Install tools
      run: |
          echo $TOOLCHAIN
          echo $CC
          echo $curlArchive