name: Release builder
run-name: Build ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*-armv7l"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build dependencies
      run: /bin/bash build-dependencies-armv7l.sh

    - name: Build ovh-dynhost
      run: /bin/bash build.sh
      
    - name: Test ovh-dynhost
      run: |
          mv build/ovh-dynhost build/ovh-dynhost-armv7l
            
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        tag_name: ${{ github.ref }}
        files: build/ovh-dynhost-armv7l
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
