name: Release builder
run-name: Build ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  
permissions:
  contents: write

jobs:
  builder-x86:
    runs-on: ubuntu-latest

    env:
      zlibArchive: 'https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.xz'
      caresArchive: 'https://github.com/c-ares/c-ares/releases/download/cares-1_19_0/c-ares-1.19.0.tar.gz'
      wolfSSLArchive: 'https://github.com/wolfSSL/wolfssl/archive/refs/tags/v5.6.0-stable.tar.gz'
      nghttp2Archive: 'https://github.com/nghttp2/nghttp2/releases/download/v1.52.0/nghttp2-1.52.0.tar.xz'
      curlArchive: 'https://github.com/curl/curl/releases/download/curl-8_0_1/curl-8.0.1.tar.xz'
      TOOLCHAIN: '$(pwd)/x86_64-linux-musl-native'
      AR: '$TOOLCHAIN/bin/x86_64-linux-musl-gcc-ar'
      AS: '$TOOLCHAIN/bin/as'
      CC: '$TOOLCHAIN/bin/x86_64-linux-musl-gcc'
      CXX: '$TOOLCHAIN/bin/x86_64-linux-musl-g++'
      LD: '$TOOLCHAIN/bin/ld'
      RANLIB: '$TOOLCHAIN/bin/x86_64-linux-musl-gcc-ranlib'
      STRIP: '$TOOLCHAIN/bin/strip'

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
          pwd
          echo $CC
          echo $TOOLCHAIN
          echo $nghttp2Archive 